### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Kansei** [Kansei/iizuka_seimenjo_r#2]
ざっくり書くと、
bundlerをインストールする。

その後、cloneしてきたディレクトリで
``bundle install --path vendor/bundler``
``rails db:migrate``
を実行する。

もし、rubyのバージョンが違うって怒られたら、そのディレクトリ内で
``rbenv install 2.5.1``
``rbenv local 2.5.1``
でいけると思う。

これだけ見てもできんと思うから記事とか見てやっといて〜

**Comment by manboumanbou** [comment]
なんとかできた！
